# Generated by Django 5.2.3 on 2025-07-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_singer', models.ImageField(upload_to='img_singer/', verbose_name='Картинка')),
                ('name_singer', models.CharField(max_length=50, verbose_name='Имя исполнителя')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_song', models.ImageField(upload_to='img_song/', verbose_name='Картинка')),
                ('name_song', models.CharField(max_length=50, verbose_name='Название песни')),
                ('file', models.FileField(upload_to='', verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='TypeMusics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_type', models.ImageField(upload_to='img_type/', verbose_name='Картинка')),
                ('name_type', models.CharField(max_length=50, verbose_name='Жанр')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=250, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
